# Generated by Django 3.1.6 on 2021-02-24 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mean',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_text', models.CharField(max_length=200)),
                ('type_text', models.CharField(max_length=10)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.word')),
            ],
        ),
    ]
