# Generated by Django 3.1.6 on 2021-02-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mean',
            old_name='mean_word',
            new_name='mean_text',
        ),
        migrations.AddField(
            model_name='mean',
            name='type_text',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
